export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const FETCH_JOURNEYMEN = 'FETCH_JOURNEYMEN';
export const CREATE_JOURNEYMAN = 'CREATE_JOURNEYMAN';
export const DELETE_JOURNEYMAN = 'DELETE_JOURNEYMAN';
