export const AUTHENTICATED = 'AUTHENTICATED'
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
export const ADD_JOURNEYMAN = 'ADD_JOURNEYMAN';
export const LOAD_JOURNEYMEN = 'LOAD_JOURNEYMEN';
export const DELETE_JOURNEYMAN = 'DELETE_JOURNEYMAN';
export const GET_JOURNEYMAN = 'GET_JOURNEYMAN';

